source "https://rubygems.org"

ruby ">= 3.1.0"

gemspec path: '../../'

gem "rails", path: "_src"
gem "sqlite3"
# gem "orthoses", path: "../../../orthoses"

if RUBY_VERSION >= "3.1"
  gem "net-smtp", require: false
  gem "net-imap", require: false
  gem "net-pop", require: false
  gem "psych", "~> 3"
end
